import Consultation from '@/Components/Consultation'
import DownloadSection from '@/Components/DownloadSection'
import Faq from '@/Components/Faq'
import HashBanner from '@/Components/HashBanner'
import HeroSection from '@/Components/Services/Brand/HeroSection'
import WhatWeDo from '@/Components/Services/Brand/WhatWeDo'
import Work from '@/Components/Services/OurWork'
import Head from 'next/head'
import React from 'react'

const IMPage = () => {
    return (
        <>
            <Head>
                <title>Brand Print & Solutions</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <>
                <HeroSection />
                <WhatWeDo />
                <HashBanner p='Let Us Create Visibile' h1='BRAND SOLUTIONS' />
                <Work/>
                <DownloadSection />
                {/*<Consultation/>*/}
                <Faq />
            </>
        </>
    )
}

export default IMPage