import MainServicePage from '@/Components/Services/MainServicePage'
import Head from 'next/head'
import React from 'react'


const index = () => {
    return (
        <>
            <Head>
                <title>Services</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <>
                <MainServicePage />
            </>
        </>
    )
}

export default index