import DownloadSection from '@/Components/DownloadSection'
import Faq from '@/Components/Faq'
import HashBanner from '@/Components/HashBanner'
import HeroSection from '@/Components/Services/InfluencerMarketing/HeroSection'
import WhatWeDo from '@/Components/Services/InfluencerMarketing/WhatWeDo'
import Head from 'next/head'
import React from 'react'

const SMMPage = () => {
    return (
        <>
            <Head>
                <title>Influencer Marketing</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <>
                <HeroSection />
                <WhatWeDo />
                <HashBanner p='Let Us Build Your' h1='ONLINE PRESENCE' />
                <DownloadSection />
                <Faq />
            </>
        </>
    )
}

export default SMMPage