import Consultation from '@/Components/Consultation'
import DownloadSection from '@/Components/DownloadSection'
import Faq from '@/Components/Faq'
import HashBanner from '@/Components/HashBanner'
import Work from '@/Components/Services/OurWork'
import HeroSection from '@/Components/Services/Photography/HeroSection'
import WhatWeDo from '@/Components/Services/Photography/WhatWeDo'
import Head from 'next/head'
import React from 'react'

const SEOPage = () => {
  return (
    <>
      <Head>
        <title>Photography & Videography</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <HeroSection />
        <WhatWeDo />
        <HashBanner p='Let Us Capture Your' h1='BRAND STORY' />
        <Work/>
        <DownloadSection />
        {/*<Consultation/>*/}
        <Faq />
      </>
    </>
  )
}

export default SEOPage