import Button from '@/Components/Button'
import Consultation from '@/Components/Consultation'
import DownloadSection from '@/Components/DownloadSection'
import Faq from '@/Components/Faq'
import HashBanner from '@/Components/HashBanner'
import Carousel from '@/Components/Home/PortfolioBlog/Carousel'
import Work from '@/Components/Services/OurWork'
import HeroSection from '@/Components/Services/Photography/HeroSection'
import WhatWeDo from '@/Components/Services/Photography/WhatWeDo'
import Head from 'next/head'
import Link from 'next/link'
import React, { useEffect, useState } from 'react'


const PHOTOPage = () => {

  const items  = [
    {
      title: `How can professional photography and videography enhance the visual appeal of my business?`,
      content: `Professional photography and videography have a significant impact on enhancing your business's visual appeal. With top-quality equipment and expertise, our in house professionals capture high-resolution images and videos that showcase your products, services, or premises in the highest visually appealing manner. We ensure consistency with your brand identity, creating a cohesive and professional look. Engaging content evokes emotions and establishes a connection with your target audience. Professionally captured visuals enhance credibility, boost social media presence, provide a marketing advantage, and offer versatility across various channels. Investing in professional visuals elevates your business and leaves a lasting impression.`,
    },
    {
      title: `How can professional photography and video benefit my marketing and advertising efforts?`,
      content: `Professional photography and video services offered by us possess several benefits for marketing and advertising. We enhance visual appeal, engage audiences, improve brand perception, and increase conversion rates through our top notch photography and videography services. These high-quality visuals also boost social media visibility and provide versatility across multiple channels. Investing in professional photography and video gives a competitive advantage and establishes a positive brand image. Embedding professional services ensures brands stand out and thrive in the digital landscape.`,
    },
    {
      title: `Can photography and video services be customized to suit my specific needs and requirements according to my lines of business and products?`,
      content: `Yes, photography and video services can be fully customized to suit your specific needs and requirements. Our in-house Professional photographers and videographers understand the importance of tailoring their services to meet unique preferences and objectives to raise brand presence and via visual marketing. We collaborate closely to understand your vision, style preferences to formulate visually appealing marketing campaigns.`,
    },
    {
      title: `How can I ensure that my photographs and videos are protected and maintained securely?`,
      content: `Ensuring the secure protection and maintenance of your photographs and videos is paramount. We take steps to safeguard your visual assets by implementing secure backup and storage solutions, utilising password protection. Watermarking your visuals prevents unauthorised use on social media platforms.`,
    },
  ]

  const [mobileView, setMobileView] = useState(false)

  useEffect(() => {
    const handleResize = () => {
      if(window.innerWidth<=500){
        setMobileView(true)
      }else{
        setMobileView(false)
      }
    };

    // Initial screen size
    handleResize();

    // Add event listener for resize
    window.addEventListener('resize', handleResize);

    // Clean up event listener on component unmount
    return () => {
      window.removeEventListener('resize', handleResize);
    };
  }, []);
  return (
    <>
      <Head>
        <title>Photography & Videography</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <HeroSection />
        <WhatWeDo />
        <HashBanner p='Let Us Capture Your' h1='BRAND STORY' />
        <Work/>
        <Carousel mobile={mobileView} />
        <div style={{display:'flex',justifyContent:'center',marginBottom:'20px'}}>
        <Link href='/Portfolio'>
        <Button
            value="View More"
            color="#ffffff"
            bg='var(--P700)'
        />
        </Link>
        </div>
        <DownloadSection />
        <Consultation/>
        <Faq items={items}/>
      </>
    </>
  )
}

export default PHOTOPage