import Button from '@/Components/Button'
import Consultation from '@/Components/Consultation'
import DownloadSection from '@/Components/DownloadSection'
import Faq from '@/Components/Faq'
import HashBanner from '@/Components/HashBanner'
import Carousel from '@/Components/Home/PortfolioBlog/Carousel'
import Work from '@/Components/Services/OurWork'
import HeroSection from '@/Components/Services/Search-Engine-Optimaization/HeroSection'
import WhatWeDo from '@/Components/Services/Search-Engine-Optimaization/WhatWeDo'
import Head from 'next/head'
import Link from 'next/link'
import React, { useEffect, useState } from 'react'

const SEOPage = () => {

  const items = [
    {
      title:'How Digital Marketing agencies show results through SEO?',
      content: `Professional SEO Company show the result through SEO strategy by key performance indicators (KPIs) and organic traffic growth, keyword rankings in search engine results pages (SERPs), backlink analysis, improved conversion rates, on-page optimization, technical SEO audits, and the use of reporting tools like Google Analytics, Google Search Console, SEMrush, Moz, Ahrefs. We provide the best results to summarise essential metrics, progress, and recommendations and we help you to understand that SEO is a long-term strategy which requires ongoing monitoring and adjustment for optimal results.`,
    },
    {
      title:' Should I use SEO services in Bangalore for my business?',
      content: `Best SEO agency in Bangalore will yield sustainable benefits for your business. We help you to enhance your website's visibility in search engine result pages, driving organic traffic and potential customers. In a competitive Bangalore market, establishing an online presence is critical. SEO services will optimise your website, targeted keywords, improve search engine rankings, and attract local customers. By amplifying online visibility and expanding your audience reach, SEO services play a main role in ranking your business in Bangalore.`,
    },
    {
      title:'Why should I choose seo and sem in digital marketing to build my brand?',
      content: `Choosing SEM in digital marketing is crucial to establish and promote your brand. A reputable SEM Agency excels in enhancing brand visibility and driving targeted traffic through strategic advertising campaigns. We leverage keyword research, optimise ad placements, and utilise data-driven insights for optimal results. Collaborating with a trusted SEM Agency grants access to expertise, resources, and industry knowledge, enabling a brand presence, relevant audience attraction, conversions, and success in the competitive digital landscape.`,
    },
    {
      title:'When will SEO search engine optimization start showing results?',
      content: `Search Engine Optimization can vary based on industry competition, website condition, SEO strategy quality, and Google algorithm updates. Typically, it takes a few weeks to a few months to observe sustainable improvements in rankings and organic traffic. However, SEO is an ongoing process that requires continuous optimization to sustain and enhance search engine visibility. Patience, persistence, and consistent optimization efforts are crucial for achieving long-term success with SEO.`,
    },
    {
      title:' Does my website need SEO services to increase the number of visitors?',
      content: `SEO services play a crucial role in increasing the number of visitors to your website. By implementing effective SEO strategies, we will enhance your website's visibility in search engine results to attract organic traffic by optimising your site's structure, content, and relevant keywords to improve search engine rankings and drive targeted traffic. This will increase visibility and targeted traffic result in higher visitor numbers, increase brand exposure, and enhanced opportunities for conversions and business expansion.`,
    },
  ]

  const [mobileView, setMobileView] = useState(false)

  useEffect(() => {
    const handleResize = () => {
      if(window.innerWidth<=500){
        setMobileView(true)
      }else{
        setMobileView(false)
      }
    };

    // Initial screen size
    handleResize();

    // Add event listener for resize
    window.addEventListener('resize', handleResize);

    // Clean up event listener on component unmount
    return () => {
      window.removeEventListener('resize', handleResize);
    };
  }, []);
  return (
    <>
      <Head>
        <title>Search Engine Optimaization</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <HeroSection />
        <WhatWeDo />
        <HashBanner p='Let Us maximise Your' h1='DIGITAL VISIBILITY' />
        <Work/>
        <Carousel mobile={mobileView} />
        <div style={{display:'flex',justifyContent:'center',marginBottom:'20px'}}>
        <Link href='/Portfolio'>
        <Button
            value="View More"
            color="#ffffff"
            bg='var(--P700)'
        />
        </Link>
        </div>
        <DownloadSection />
        <Consultation/>
        <Faq items={items}/>
      </>
    </>
  )
}

export default SEOPage