import Consultation from '@/Components/Consultation'
import DownloadSection from '@/Components/DownloadSection'
import Faq from '@/Components/Faq'
import HashBanner from '@/Components/HashBanner'
import Carousel from '@/Components/Home/PortfolioBlog/Carousel'
import Work from '@/Components/Services/OurWork'
import HeroSection from '@/Components/Services/Social Media Marketing/HeroSection'
import WhatWeDo from '@/Components/Services/Social Media Marketing/WhatWeDo'
import Head from 'next/head'
import React from 'react'

const SMMPage = () => {
  return (
    <>
      <Head>
        <title>Socail Media Marketing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <HeroSection />
        <WhatWeDo />
        <HashBanner p='Let Us Ignite Your' h1='SOCAIL PRESENCE' />
        <Work/>
        <Carousel />
        <DownloadSection />
        {/*<Consultation/>*/}
        <Faq />
      </> 
    </>
  )
}

export default SMMPage