import Button from '@/Components/Button'
import Consultation from '@/Components/Consultation'
import DownloadSection from '@/Components/DownloadSection'
import Faq from '@/Components/Faq'
import HashBanner from '@/Components/HashBanner'
import Carousel from '@/Components/Home/PortfolioBlog/Carousel'
import Work from '@/Components/Services/OurWork'
import HeroSection from '@/Components/Services/WebsiteDevelopment/HeroSection'
import WhatWeDo from '@/Components/Services/WebsiteDevelopment/WhatWeDo'
import Head from 'next/head'
import Link from 'next/link'
import React, { useEffect, useState } from 'react'

const WDPage = () => {

  const items = [
    {
      title:'What is the advantage of hiring the best eCommerce development company for my website?',
      content: `Digital Marketing Agency near me provides the best eCommerce website that offers several advantages. With our expertise we ensure a tailored user-friendly website with essential features like secure payment gateways. We optimise websites for mobile devices, implement SEO-friendly structures, and provide ongoing support and enhanced security measures. We Collaborate with a reputable eCommerce development company and drive conversions, sales, and business growth in the competitive eCommerce landscape.`,
    },
    {
      title:'How to get the best designs with WordPress web development services in Bangalore?',
      content: `We achieve the best designs with WordPress web development services in Bangalore, we do research and shortlist the reputable providers and evaluate their design expertise and prioritise effective communication. Inquire about customizations and responsive design. Emphasise user-friendly and intuitive designs. Collaborate with the development team through feedback and iterations. Set clear expectations for timelines and deliverables. we Follow these steps to ensure exceptional designs for your WordPress website in Bangalore.`,
    },
    {
      title:'What is the time frame taken by a website development company in Bangalore to design and develop a website?',
      content: `The timeline for website design and development varies based on factors like complexity and required functionalities. Simple websites typically take around 4-8 weeks, while complex ones may take 8-16 weeks or longer. Discuss your specific requirements with us to get a more accurate estimate.`,
    },
    {
      title:'Should I go for professional website development services in bangalore?',
      content: `Opting for professional website development services is highly recommended. Professional developers possess the expertise, experience, and knowledge required to create a high-quality, visually appealing, and functional website. We stay up to date with the latest design trends and coding standards, ensuring your website is optimised for performance and search engine visibility. Professional development saves time and allows you to focus on your business while leaving the technical aspects to experts. It's a worthwhile investment for a successful online presence.`,
    },
    {
      title:'Is web content development a part of website design?',
      content: `Web content development is an essential component of website design. It involves creating and organising textual and multimedia content on the website. This includes writing engaging copy, organising content logically, and incorporating relevant media elements. Effective web content development ensures a cohesive user experience, communicates the brand message, and engages website visitors.`,
    },
  ]

  const [mobileView, setMobileView] = useState(false)

  useEffect(() => {
    const handleResize = () => {
      if(window.innerWidth<=500){
        setMobileView(true)
      }else{
        setMobileView(false)
      }
    };

    // Initial screen size
    handleResize();

    // Add event listener for resize
    window.addEventListener('resize', handleResize);

    // Clean up event listener on component unmount
    return () => {
      window.removeEventListener('resize', handleResize);
    };
  }, []);
  return (
    <>
      <Head>
        <title>Website Development</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <HeroSection />
        <WhatWeDo />
        <HashBanner p='Let Us Create Your' h1='ONLINE IDENTITY' />
        <Work/>
        <Carousel mobile={mobileView} />
        <div style={{display:'flex',justifyContent:'center',marginBottom:'20px'}}>
        <Link href='/Portfolio'>
        <Button
            value="View More"
            color="#ffffff"
            bg='var(--P700)'
        />
        </Link>
        </div>
        <DownloadSection />
        <Consultation/>
        <Faq items={items}/>
      </>
    </>
  )
}

export default WDPage