import Consultation from '@/Components/Consultation'
import DownloadSection from '@/Components/DownloadSection'
import Faq from '@/Components/Faq'
import HashBanner from '@/Components/HashBanner'
import Work from '@/Components/Services/OurWork'
import HeroSection from '@/Components/Services/WebsiteDevelopment/HeroSection'
import WhatWeDo from '@/Components/Services/WebsiteDevelopment/WhatWeDo'
import Head from 'next/head'
import React from 'react'

const SMMPage = () => {
  return (
    <>
      <Head>
        <title>Website Development</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <HeroSection />
        <WhatWeDo />
        <HashBanner p='Let Us Create Your' h1='ONLINE IDENTITY' />
        <Work/>
        <DownloadSection />
        {/*<Consultation/>*/}
        <Faq />
      </>
    </>
  )
}

export default SMMPage