import HeroSection from '@/Components/About us/HeroSection'
import DownloadSection from '@/Components/DownloadSection'
import Faq from '@/Components/Faq'
import HashBanner from '@/Components/HashBanner'
import Head from 'next/head'
import React from 'react'

const AboutUs = () => {
  return (
    <>
      <Head>
        <title>About Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <HeroSection />
        <HashBanner p='Let Us Build Your' h1='ONLINE PRESENCE' />
        <DownloadSection />
        <Faq />
      </>
    </>
  )
}

export default AboutUs