import Faq from '@/Components/Faq'
import Head from 'next/head'
import React from 'react'
import ContactForm from '@/Components/Contact us/Form'
import LocateUs from '@/Components/Contact us/Location'

const ContactUs = () => {
  return (
    <>
      <Head>
        <title>Contact Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <ContactForm />
        <LocateUs />
        <Faq />
      </>
    </>
  )
}

export default ContactUs;