import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import HeroSection from '@/Components/HeroSection'
import Services from '@/Components/Services'
import Review from '@/Components/Review'
import Portfolio from '@/Components/Portfolio'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
      <HeroSection />
      <Services />
      <Review />
      <Portfolio />
      </>
    </>
  )
}
