import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import HeroSection from '@/Components/HeroSection'
import Services from '@/Components/Services'
import Review from '@/Components/Review'
import WhySocialAgent from '@/Components/WhySocialAgent'
import HashBanner from '@/Components/HashBanner'
import DownloadSection from '@/Components/DownloadSection'
import PortfolioBlogs from '@/Components/PortfolioBlogs'
import { useEffect, useState } from 'react'
import Faq from '../Components/Faq'


export default function Home() {
  const [title, setTitle] = useState('Social Agent')
  useEffect(() => {
    window.onblur = function () {
      setTitle('Come back!');
    }
    window.onfocus = function () {
      setTitle('Social Agent');
    }
  }, [title])
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <HeroSection />
        <WhySocialAgent />
        <Services />
        <HashBanner p='Your Digital Bridge To' h1='SUCCESS' />
        <PortfolioBlogs />
        <Review />
        <DownloadSection />
        <Faq />
      </>
    </>
  )
}
